USER-SUPPLIED VALUES:
backend:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
compactor:
  replicas: 1
deploymentMode: Distributed
distributor:
  maxUnavailable: 2
  replicas: 3
gateway:
  service:
    type: LoadBalancer
indexGateway:
  maxUnavailable: 1
  replicas: 2
ingester:
  replicas: 3
  zoneAwareReplication:
    enabled: false
loki:
  auth_enabled: false
  ingester:
    chunk_encoding: snappy
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  pattern_ingester:
    enabled: true
  querier:
    max_concurrent: 4
  schemaConfig:
    configs:
    - from: "2024-04-01"
      index:
        period: 24h
        prefix: loki_index_
      object_store: s3
      schema: v13
      store: tsdb
minio:
  enabled: true
querier:
  maxUnavailable: 2
  replicas: 3
queryFrontend:
  maxUnavailable: 1
  replicas: 2
queryScheduler:
  replicas: 2
read:
  replicas: 0
singleBinary:
  replicas: 0
write:
  replicas: 0
